import "server-only";
/**
 * Blog data is loaded from a build-time JSON manifest (`blog-manifest.generated.json`),
 * not from the filesystem at runtime. Cloudflare Workers have no `fs` for `content/blog/`.
 *
 * The manifest is generated by `scripts/generate-blog-manifest.mjs` (runs on `postinstall`,
 * `prebuild`, and `npm run dev`). Post bodies are pre-compiled to HTML there so the Worker
 * never runs MDX compilation at request time.
 */
import { isPillarSlug, type PillarSlug } from "./blog-pillars";
import manifest from "./blog-manifest.generated.json";

export type PostFrontmatter = {
  title: string;
  description: string;
  slug: string;
  date: string;
  updated?: string;
  author: string;
  pillar: PillarSlug;
  tags: string[];
  cover?: string;
  draft?: boolean;
};

export type Post = {
  frontmatter: PostFrontmatter;
  content: string;
  compiledHtml: string;
  readingTime: string;
  readingMinutes: number;
};

const _posts: Post[] = (manifest as Post[]).filter(
  (p) => isPillarSlug(p.frontmatter.pillar) && !p.frontmatter.draft,
);

export function getAllPosts(): Post[] {
  return _posts;
}

export function getPostBySlug(slug: string): Post | null {
  return _posts.find((p) => p.frontmatter.slug === slug) ?? null;
}

export function getPostsByPillar(pillar: PillarSlug): Post[] {
  return _posts.filter((p) => p.frontmatter.pillar === pillar);
}

export function getRelatedPosts(slug: string, limit = 3): Post[] {
  const current = _posts.find((p) => p.frontmatter.slug === slug);
  if (!current) return [];
  const samePillar = _posts.filter(
    (p) => p.frontmatter.slug !== slug && p.frontmatter.pillar === current.frontmatter.pillar,
  );
  if (samePillar.length >= limit) return samePillar.slice(0, limit);
  const fillers = _posts.filter(
    (p) => p.frontmatter.slug !== slug && p.frontmatter.pillar !== current.frontmatter.pillar,
  );
  return [...samePillar, ...fillers].slice(0, limit);
}

export function getAllSlugs(): string[] {
  return _posts.map((p) => p.frontmatter.slug);
}
